### ISSUE TITLE
Struktura katalogów

### ISSUE THREAD

**Issue by krzysztoftrol** [olaciesielska/web-project#3]

**Comment by kubaty007** [comment]
- [ ] - niektóre zdjęcia są powielone w folderach np. producent.png
![image](https://user-images.githubusercontent.com/62720503/236741070-87f7bd37-7fe0-4b2f-97d6-77de8fa275bb.png)

- [ ] - uporządkowanie plików w folderach np. pliki svg znajdują się w dwóch folderach - ico oraz dodatki_1. Można to uporządkować i wrzucić do jednego katalogu
![image](https://user-images.githubusercontent.com/62720503/236741488-3a155e6b-e389-4833-bb59-958f0e3432e0.png)


- [ ] - zmiana nazw folderów tak, aby lepiej opisywały co się w nich znajduje np. `scss` oraz `css` jest jasne, a `etap_01_2` niekoniecznie
![image](https://user-images.githubusercontent.com/62720503/236741763-d865d9f2-8cb1-4436-ae63-466b2311f456.png)

**Comment by kubaty007** [comment]
# Poprawki

- [ ] - te dwa foldery mają takie samo przeznaczenie, myślę, że można połączyć je w jeden folder i usunąć duplikaty
![Image](https://github.com/olaciesielska/web-project/assets/62720503/a6f95c6c-f41f-4b46-b849-a5ab2e59a90b)
