### ISSUE TITLE
[HOME] Banerki

### ISSUE THREAD

**Issue by krzysztoftrol** [olaciesielska/web-project#6]

**Comment by kubaty007** [comment]
# Poprawki

### Mobile

- [ ] - pierwszy banner 'chowa się' pod sliderem
![Image](https://github.com/olaciesielska/web-project/assets/62720503/d1e9ac5d-56cd-4c65-8e1c-40e56ce118ea)

- [ ] - tekst w przyciskach na bannerkach jest minimalnie za wysoko, można wyśrodkować go w pionie



### Desktop (nie testowane)

**Comment by kubaty007** [comment]
# Poprawki

- [ ] - na mobile do zmniejszenia paddingi containera np.15px
