### ISSUE TITLE
[HOME] Slider produktowy

### ISSUE THREAD

**Issue by krzysztoftrol** [olaciesielska/web-project#7]

**Comment by kubaty007** [comment]
# Poprawki

- [ ] - przyciski do dostosowania
![Image](https://github.com/olaciesielska/web-project/assets/62720503/d96879ae-6d96-4f50-82f2-9b914969026f)

- [ ] - elementy html możesz przechowywać w stałych (const)
![Image](https://github.com/olaciesielska/web-project/assets/62720503/45ce0637-f382-4bb7-a56f-39e7241b1fa2)

**Comment by kubaty007** [comment]
# Poprawki:

- [ ] - fajnie jakby tutaj też było widać kafelki
![Image](https://github.com/olaciesielska/web-project/assets/62720503/e31c0e90-60c2-44a4-b262-c377965e0e80)
