### ISSUE TITLE
[HOME] Baner dlaczego my

### ISSUE THREAD

**Issue by krzysztoftrol** [olaciesielska/web-project#8]

**Comment by kubaty007** [comment]
# Poprawki:
- [ ] - zdjecie w tle na 100% szerokosci (poza container) [podpowiedź](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)
![Image](https://github.com/olaciesielska/web-project/assets/62720503/41fe046e-1385-4fde-bfa1-b3f6e75dad0f)

**Comment by kubaty007** [comment]
# Poprawki
- [ ] - na mobile zrobić tak, by nagłówek mieścił się w jednej linii (320px)
- [ ] - inline style do przeniesienia do scss
- [ ] - użycie pseudoelementu do wytworzenia kreski pod nagłówkiem
